### ISSUE TITLE
Bug: speaker section looks broken on mobile 

### ISSUE THREAD

**Issue by drublic** [nightlybuild-conference/nightlybuild-io-2016#17]
Please see the screenshot below.

![screen shot 2016-08-18 at 10 47 39](https://cloud.githubusercontent.com/assets/502487/17767697/3f9ae22e-6531-11e6-9b3f-19aaeb1b026d.png)

**Comment by ixisio** [comment]
fixed ✅ 

https://nightlybuild.io/speakers
